spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demodatabase
    username: root
    password: helloworld

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true